cd ./repo1 # //change the directory to repo1

# W/O constraints
## CartPole
python train.py --total_timesteps 5e5 --format_str tensorboard --policy_eval_interval 5000 --n_eval_envs 10 --n_envs 8 --elbo_steps 1 --policy flow --rl_algo A2C_Flow --batch_size_flow_updating 256 --n_samples_prob_est 1 --act_encoding_scheme one_hot --seed 3407 --normalize True --env_id CartPole-v1 --posterior_type normal --cond_bijection True

## Acrobot
python train.py --total_timesteps 1e6 --format_str tensorboard --policy_eval_interval 5000 --n_eval_envs 10 --policy flow --rl_algo A2C_Flow --flow_type shallow_coupling --act_encoding_scheme one_hot --elbo_steps 1 --seed 3407 --env_id Acrobot-v1 --num_flow_layers 4 --normalize True --batch_size_flow_updating 256 --gamma 0.995 --n_samples_prob_est 4 --posterior_type flow --cond_bijection True --n_envs 8 --n_steps 1 --ensemble_mode cond_weight_2

## Pistonball: including v1-v3.
python train.py --total_timesteps 2e6 --format_str tensorboard --policy_eval_interval 5000 --n_eval_envs 10 -fea_ext naturecnn --seed 3407 --env_id Pistonball-v1 --rl_algo A2C_Flow --policy flow --flow_type shallow_coupling --act_encoding_scheme one_hot --elbo_steps 1 --num_flow_layers 4 --normalize True --batch_size_flow_updating 512 --n_samples_prob_est 4 --posterior_type flow --cond_bijection True --n_envs 64 --n_steps 1 --ensemble_mode cond_weight_2
python train.py --total_timesteps 2e6 --format_str tensorboard --policy_eval_interval 5000 --n_eval_envs 10 -fea_ext naturecnn --seed 3407 --env_id Pistonball-v2 --rl_algo A2C_Flow --policy flow --flow_type shallow_coupling --act_encoding_scheme one_hot --elbo_steps 1 --num_flow_layers 4 --normalize True --batch_size_flow_updating 512 --n_samples_prob_est 4 --posterior_type flow --cond_bijection True --n_envs 64 --n_steps 1 --ensemble_mode cond_weight_2
python train.py --total_timesteps 2e6 --format_str tensorboard --policy_eval_interval 5000 --n_eval_envs 10 -fea_ext naturecnn --seed 3407 --env_id Pistonball-v3 --rl_algo A2C_Flow --policy flow --flow_type shallow_coupling --act_encoding_scheme one_hot --elbo_steps 1 --num_flow_layers 4 --normalize True --batch_size_flow_updating 512 --n_samples_prob_est 4 --posterior_type flow --cond_bijection True --n_envs 64 --n_steps 1 --ensemble_mode cond_weight_2

## ERA: including v5
python train.py --total_timesteps 1e6 --format_str tensorboard --policy_eval_interval 5000 --n_eval_envs 10 --rl_algo A2C_Flow --policy flow --flow_type shallow_coupling --act_encoding_scheme one_hot --elbo_steps 1 --seed 3407 -fea_ext gnn --embedding_vars_gnn_extractor 2 1 3 3 2 1 --env_id SeqSSG-no-cstr-v5 --num_flow_layers 4 --normalize False --normalize_obs False --batch_size_flow_updating 512 --n_samples_prob_est 4 --posterior_type flow --cond_bijection True --n_envs 64 --n_steps 1 --ensemble_mode cond_weight_2

# W/ constraints
## ERA: including v1-v5
python train.py --total_timesteps 7e5 --format_str tensorboard --policy_eval_interval 5000 --n_eval_envs 10 --policy flow --rl_algo A2C_Rej --flow_type shallow_coupling --act_encoding_scheme one_hot --elbo_steps 1 --seed 3407 -fea_ext gnn --embedding_vars_gnn_extractor 2 1 3 3 2 1 --env_id SeqSSG-v1 --num_flow_layers 4 --normalize False --normalize_obs False --batch_size_flow_updating 256 --n_samples_prob_est 4 --posterior_type flow --cond_bijection True --min_n_samples_inv_rej 32 --n_envs 64 --n_steps 1 --ensemble_mode cond_weight_2
python train.py --total_timesteps 7e5 --format_str tensorboard --policy_eval_interval 5000 --n_eval_envs 10 --policy flow --rl_algo A2C_Rej --flow_type shallow_coupling --act_encoding_scheme one_hot --elbo_steps 1 --seed 3407 -fea_ext gnn --embedding_vars_gnn_extractor 2 1 3 3 2 1 --env_id SeqSSG-v2 --num_flow_layers 4 --normalize False --normalize_obs False --batch_size_flow_updating 256 --n_samples_prob_est 4 --posterior_type flow --cond_bijection True --min_n_samples_inv_rej 32 --n_envs 64 --n_steps 1 --ensemble_mode cond_weight_2
python train.py --total_timesteps 7e5 --format_str tensorboard --policy_eval_interval 5000 --n_eval_envs 10 --policy flow --rl_algo A2C_Rej --flow_type shallow_coupling --act_encoding_scheme one_hot --elbo_steps 1 --seed 3407 -fea_ext gnn --embedding_vars_gnn_extractor 2 1 3 3 2 1 --env_id SeqSSG-v3 --num_flow_layers 4 --normalize False --normalize_obs False --batch_size_flow_updating 256 --n_samples_prob_est 4 --posterior_type flow --cond_bijection True --min_n_samples_inv_rej 32 --n_envs 64 --n_steps 1 --ensemble_mode cond_weight_2
python train.py --total_timesteps 7e5 --format_str tensorboard --policy_eval_interval 5000 --n_eval_envs 10 --policy flow --rl_algo A2C_Rej --flow_type shallow_coupling --act_encoding_scheme one_hot --elbo_steps 1 --seed 3407 -fea_ext gnn --embedding_vars_gnn_extractor 2 1 3 3 2 1 --env_id SeqSSG-v4 --num_flow_layers 4 --normalize False --normalize_obs False --batch_size_flow_updating 256 --n_samples_prob_est 4 --posterior_type flow --cond_bijection True --min_n_samples_inv_rej 32 --n_envs 64 --n_steps 1 --ensemble_mode cond_weight_2
python train.py --total_timesteps 7e5 --format_str tensorboard --policy_eval_interval 5000 --n_eval_envs 10 --policy flow --rl_algo A2C_Rej --flow_type shallow_coupling --act_encoding_scheme one_hot --elbo_steps 1 --seed 3407 -fea_ext gnn --embedding_vars_gnn_extractor 2 1 3 3 2 1 --env_id SeqSSG-v5 --num_flow_layers 4 --normalize False --normalize_obs False --batch_size_flow_updating 256 --n_samples_prob_est 4 --posterior_type flow --cond_bijection True --min_n_samples_inv_rej 32 --n_envs 64 --n_steps 1 --ensemble_mode cond_weight_2

cd .. ; cd ./repo2 # //change the directory to repo2

## Pistonball: including v1, v2
python train.py --total_timesteps 2e6 --format_str tensorboard --policy_eval_interval 5000 --n_eval_envs 10 --policy flow --rl_algo A2C_Rej --flow_type shallow_coupling --act_encoding_scheme one_hot --elbo_steps 1 --seed 3407 -fea_ext combineddummy --env_id PistonballCstr-v1 --num_flow_layers 4 --norm_obs_keys observation --normalize True --batch_size_flow_updating 512 --n_samples_prob_est 4 --posterior_type flow --cond_bijection True --min_n_samples_inv_rej 64 --n_envs 64 --n_steps 1 --ensemble_mode mean
python train.py --total_timesteps 2e6 --format_str tensorboard --policy_eval_interval 5000 --n_eval_envs 10 --policy flow --rl_algo A2C_Rej --flow_type shallow_coupling --act_encoding_scheme one_hot --elbo_steps 1 --seed 3407 -fea_ext combineddummy --env_id PistonballCstr-v2 --num_flow_layers 4 --norm_obs_keys observation --normalize True --batch_size_flow_updating 512 --n_samples_prob_est 2 --posterior_type flow --cond_bijection True --min_n_samples_inv_rej 64 --n_envs 64 --n_steps 1 --ensemble_mode cond_weight_2
